### PR TITLE
UR encode library

### PR DESCRIPTION
**Pull request by gorazdko**
## Abstract

Implementation according to https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md

## Status

~Ready for review~

WIP: UR spec changed, this implementation needs update

### CODE REVIEW

**Comment by gorazdko** [comment]
This is now on par with https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md acd286b

I didnt really understand the `nominal fragment length` but the tests say it's correct.

I couldnt use the latest `bc-bytewords` because the later commits (moving crc32 to different repo) broke the Arduino build, so now 2 dependencies need to be patched. I will fix it some time later when the functionality of the library changes, otherwise we'd just be moving back and forth with these small changes.

Something what I would like to see in the UR library is having fragments of (about) equal size. Having the last fragment much smaller causes displays of hardware wallets look like glitching when running qr animations. I remember that was so annoying to me that in Specter I implemented a simple algo to split the payload into (about) equal parts. It's not superb algo, it only works good for max_fragment_size > 300 bytes (in qr binary encoding), but I'm sure one can come up with something better.

https://github.com/cryptoadvance/specter-diy/blob/2e82bdc1efa36963bd980d58a641722a211362bd/src/gui/components.py#L166

cc: @wolfmcnally

**Comment by wolfmcnally** [comment]
@gorazdko bc-crypto-base does now include the CRC32 calculation, and I also moved the changes necessary to make it Arduino-compatible there.

I am aware of the need for the UR parts to be approximately the same size, and this is a requirement for fountain codes, which I am working on now. I have code I can send you in Mathematica or Swift that finds the most-even partition size given a minimum and maximum, and the algorithm will end up in the reference UR implementations that I'm working on. It's currently a straightforward linear search, because I don't expect it to be a bottleneck (it only runs once per transmission) but it could be further optimized to use a binary search.

**Comment by gorazdko** [comment]
> bc-crypto-base does now include the CRC32 calculation, and I also moved the changes necessary to make it Arduino-compatible there.

Specifically, the inclusion `#include <bc-crypto-base/bc-crypto-base.h>` breaks the build and `memory.h` is not removed, neither guarded against Arduino macro

> the algorithm will end up in the reference UR implementations that I'm working on

Great, I will update the code once available.

@ChristopherA I'd prefer this to be reviewed and merged. I am focusing now on libwally integration into Arduino. I suggest you fork the repo into BlockchainCommons, it's possible however that I reference it to the original repo.

**Comment by ChristopherA** [comment]
@ksedgwic you are the lead here, should I go ahead and merge to master?

**Comment by ksedgwic** [comment]
I'm seeing:
```
Alternatives for bc-bech32.h: []ur:5:23: fatal error: bc-bech32.h: No such file or directory
```

will need to investigate further ...

**Comment by ksedgwic** [comment]
Confused about `bc-bech32`, is it supposed to be a dependency?

**Comment by gorazdko** [comment]
Thanks, I force-pushed the fix. Also made a minor modification in function description.

`bc-bech32` should've been in 4f2893d  and deleted once bytewords replaced `bc32`. I forgot, so it was never in the repo in the first place. This is another reason to squash the commits to ensure bisectability.

**Comment by gorazdko** [comment]
> Looks good; builds and runs.

Thank you Ken for your review and testing. The UR spec changed dramatically just recently and so I will work in the next couple of days and try to catch up with the spec on this branch. I will ask you to re-review once I'm finished. I've updated the status to WIP

**Comment by gorazdko** [comment]
moved implementation to #49

**Pull request closed without merging**
