### PR TITLE
Allow invalid bip39 mnemonic, add cosigner

### LINKED ISSUE #59: Add documentation on adding TRNG entropy
I don’t see a screenshot of adding TRNG entropy in https://github.com/BlockchainCommons/bc-lethekit/blob/master/seedtool/README.md

### PR DESCRIPTION
**Pull request by gorazdko**
## Abstract

Supercedes #58

The name chosen for the procedure is `BIP39 sentence completion`. The name and word usage is not set in stone and will be updated according to the 
resolution of https://github.com/BlockchainCommons/Airgapped-Wallet-Community/discussions/27

The guide can be seen rendered here and uses a reference to Rudefox ShowMyWork lookup tables:
https://github.com/gorazdko/bc-lethekit/blob/dd3d47e7704e5856d3327c0e16a97063b40f3a57/seedtool/doc/bip39_sentence_completion.md

Added cosigner

Also improvements in documentation:
* Close #59
* build script outputs possible errors in red
* install/build documents now contain section `Next steps` so that user can follow them more easily

## Status 

ready for review

### CODE REVIEW

**Review by ChristopherA — COMMENTED** [review]
Why default to testnet?

**Comment by gorazdko** [comment]
linking test report of my own I did with Guardian and GC: https://gist.github.com/gorazdko/0c3f04f50962235e0439be6398e83393

**Comment by kkdao** [comment]
tACK

**Comment by ChristopherA** [comment]
@gorazdko, ready for me to merge?

**Review by ChristopherA — APPROVED** [review]
Will merge with tACK.

**Comment by gorazdko** [comment]
@ChristopherA please do merge.

There are also 4 PRs in bc-keytool-cli waiting to be merged.

**Pull request merged**
